In [1]:
range(3)

range(0, 3)

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [7]:
r = range(10)
r

range(0, 10)

In [9]:
range(10,40)

range(10, 40)

In [11]:
range(10,40,5)

range(10, 40, 5)

In [13]:
r1 = range(10,40,6)
r1

range(10, 40, 6)

In [15]:
for i in r1:
        print(i)

10
16
22
28
34


Numpy

In [19]:
  import numpy as np

In [23]:
np.version

<module 'numpy.version' from 'C:\\Users\\phars\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [25]:
np.__version__

'1.26.4'

In [27]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

Creating array

In [33]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [36]:
type(my_list)

list

In [38]:
arr = np.array(my_list) # we converted list to array (my list is argument i passes)
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
np. # we only learn imporatnt function

In [40]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
np.arange(3.0)

array([0., 1., 2.])

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [48]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [50]:
np.arange(20,10) # 1st arg < 2nd argu (1st arg is alwyas less than 2nd arg)

array([], dtype=int32)

In [52]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [54]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [56]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [58]:
np.arange(30,20)# alwyas less than 2nd arg

array([], dtype=int32)

In [64]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [66]:
np.arange(10,10) # we can not call equal always ,distance is nothing so cant print

array([], dtype=int32)

In [72]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [74]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [76]:
np.zeros(3) #parameter tunning 

array([0., 0., 0.])

In [82]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [84]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [88]:
np.zeros((2,10)) # means 2d array (by deafult float)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [90]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [94]:
zero = np.zeros([2,2])
print(zero)

[[0. 0.]
 [0. 0.]]


In [96]:
np.ones(3)

array([1., 1., 1.])

In [98]:
np.ones(4)

array([1., 1., 1., 1.])

In [100]:
np.ones(4, dtype=int) # when we want to integer value then use dtype=int

array([1, 1, 1, 1])

In [102]:
np.twos((2,3)) # no attribute like this in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [104]:
np.ones(3)

array([1., 1., 1.])

In [106]:
rand(3,2)

NameError: name 'rand' is not defined

In [110]:
rand(3,2)
random.rand(3,20)

NameError: name 'rand' is not defined

In [112]:
np.random.rand(5) #rand is function we call from random

array([0.97068422, 0.42575881, 0.21073601, 0.65133972, 0.61115104])

In [ ]:
module.function gives error ) package.module.function

In [114]:
np.random.rand(5)

array([0.53212326, 0.4712059 , 0.19670277, 0.62830214, 0.6943266 ])

In [121]:
np.random.rand(2,5)

array([[0.16129874, 0.69162272, 0.52794782, 0.16932323, 0.16837746],
       [0.97442271, 0.6612061 , 0.27615089, 0.52238121, 0.62739088]])

In [123]:
np.random.randint(2,4) #return random integer

3

In [129]:
np.random.randint(2,20) #2nd argument is exlusive

5

In [131]:
np.random.randint(0,1)# 0 is inclusive and 1 is exclusive

0

In [133]:
np.random.randint(10,20,5)

array([16, 19, 18, 11, 14])

In [9]:
 import numpy as np

In [11]:
np.arange(1,13).reshape(3,4) # we multiply 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
np.arange(1,13).reshape(5,4) # 13 

ValueError: cannot reshape array of size 12 into shape (5,4)

In [15]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [17]:
np.arange(1,13).reshape(12,1)# multiplocation of rehsape value and match with arrange value

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [19]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Slicing in matrix

In [21]:
b = np.random.randint(10,20,(5,4))
b

array([[18, 16, 11, 16],
       [17, 18, 18, 15],
       [18, 12, 16, 11],
       [13, 15, 11, 14],
       [14, 15, 13, 14]])

In [24]:
type(b)

numpy.ndarray

In [26]:
b

array([[18, 16, 11, 16],
       [17, 18, 18, 15],
       [18, 12, 16, 11],
       [13, 15, 11, 14],
       [14, 15, 13, 14]])

In [28]:
b[:] #all matrix display

array([[18, 16, 11, 16],
       [17, 18, 18, 15],
       [18, 12, 16, 11],
       [13, 15, 11, 14],
       [14, 15, 13, 14]])

In [30]:
b[1:3]

array([[17, 18, 18, 15],
       [18, 12, 16, 11]])

In [32]:
b

array([[18, 16, 11, 16],
       [17, 18, 18, 15],
       [18, 12, 16, 11],
       [13, 15, 11, 14],
       [14, 15, 13, 14]])

In [34]:
b[1,2] #disply speciifc value of assign element of assign row

18

In [36]:
b

array([[18, 16, 11, 16],
       [17, 18, 18, 15],
       [18, 12, 16, 11],
       [13, 15, 11, 14],
       [14, 15, 13, 14]])

In [38]:
b[1,3]

15

In [40]:
b[1,-1]

15

In [42]:
b[2:3] # gives entire row

array([[18, 12, 16, 11]])

In [44]:
b[0:-2]

array([[18, 16, 11, 16],
       [17, 18, 18, 15],
       [18, 12, 16, 11]])

In [46]:
b[0,2]

11

In [48]:
b[-5,-3]

16

In [50]:
b[-4,2]

18

Operations

In [53]:
a = np.random.randint(10,20,10)
a

array([15, 14, 18, 14, 16, 14, 18, 13, 10, 13])

In [55]:
id(a)

2462376528080

In [61]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[45, 55, 54, 59, 89, 54, 51, 19, 76, 74],
       [39,  9, 95, 63, 26, 82, 76, 29, 13, 95],
       [41, 94, 88, 22,  4, 69, 39, 68, 52, 52],
       [36, 72, 19, 59, 30, 78, 20, 85, 37, 56],
       [31, 25, 87, 57, 56, 48,  6, 66, 62, 83],
       [ 1, 18,  0, 18, 99, 20,  3, 49,  1, 50],
       [43, 74,  0, 14, 99, 73, 30, 55, 28, 72],
       [47, 45, 23, 56, 48, 91, 92, 48, 16, 37],
       [20, 80, 18, 41, 73, 39, 71, 27, 84, 63],
       [36, 22, 25, 37, 79, 51, 31, 80, 17, 80]])

In [63]:
arr2[:]

array([[45, 55, 54, 59, 89, 54, 51, 19, 76, 74],
       [39,  9, 95, 63, 26, 82, 76, 29, 13, 95],
       [41, 94, 88, 22,  4, 69, 39, 68, 52, 52],
       [36, 72, 19, 59, 30, 78, 20, 85, 37, 56],
       [31, 25, 87, 57, 56, 48,  6, 66, 62, 83],
       [ 1, 18,  0, 18, 99, 20,  3, 49,  1, 50],
       [43, 74,  0, 14, 99, 73, 30, 55, 28, 72],
       [47, 45, 23, 56, 48, 91, 92, 48, 16, 37],
       [20, 80, 18, 41, 73, 39, 71, 27, 84, 63],
       [36, 22, 25, 37, 79, 51, 31, 80, 17, 80]])

In [65]:
arr2[0:5]

array([[45, 55, 54, 59, 89, 54, 51, 19, 76, 74],
       [39,  9, 95, 63, 26, 82, 76, 29, 13, 95],
       [41, 94, 88, 22,  4, 69, 39, 68, 52, 52],
       [36, 72, 19, 59, 30, 78, 20, 85, 37, 56],
       [31, 25, 87, 57, 56, 48,  6, 66, 62, 83]])

In [69]:
arr2[1,4]

26

In [71]:
arr2[::-1] # revwerse the matrix

array([[36, 22, 25, 37, 79, 51, 31, 80, 17, 80],
       [20, 80, 18, 41, 73, 39, 71, 27, 84, 63],
       [47, 45, 23, 56, 48, 91, 92, 48, 16, 37],
       [43, 74,  0, 14, 99, 73, 30, 55, 28, 72],
       [ 1, 18,  0, 18, 99, 20,  3, 49,  1, 50],
       [31, 25, 87, 57, 56, 48,  6, 66, 62, 83],
       [36, 72, 19, 59, 30, 78, 20, 85, 37, 56],
       [41, 94, 88, 22,  4, 69, 39, 68, 52, 52],
       [39,  9, 95, 63, 26, 82, 76, 29, 13, 95],
       [45, 55, 54, 59, 89, 54, 51, 19, 76, 74]])

In [73]:
arr2

array([[45, 55, 54, 59, 89, 54, 51, 19, 76, 74],
       [39,  9, 95, 63, 26, 82, 76, 29, 13, 95],
       [41, 94, 88, 22,  4, 69, 39, 68, 52, 52],
       [36, 72, 19, 59, 30, 78, 20, 85, 37, 56],
       [31, 25, 87, 57, 56, 48,  6, 66, 62, 83],
       [ 1, 18,  0, 18, 99, 20,  3, 49,  1, 50],
       [43, 74,  0, 14, 99, 73, 30, 55, 28, 72],
       [47, 45, 23, 56, 48, 91, 92, 48, 16, 37],
       [20, 80, 18, 41, 73, 39, 71, 27, 84, 63],
       [36, 22, 25, 37, 79, 51, 31, 80, 17, 80]])

In [75]:
arr2[::-2]

array([[36, 22, 25, 37, 79, 51, 31, 80, 17, 80],
       [47, 45, 23, 56, 48, 91, 92, 48, 16, 37],
       [ 1, 18,  0, 18, 99, 20,  3, 49,  1, 50],
       [36, 72, 19, 59, 30, 78, 20, 85, 37, 56],
       [39,  9, 95, 63, 26, 82, 76, 29, 13, 95]])

In [77]:
arr2[::-3]

array([[36, 22, 25, 37, 79, 51, 31, 80, 17, 80],
       [43, 74,  0, 14, 99, 73, 30, 55, 28, 72],
       [36, 72, 19, 59, 30, 78, 20, 85, 37, 56],
       [45, 55, 54, 59, 89, 54, 51, 19, 76, 74]])

In [81]:
arr2[:-3]

array([[45, 55, 54, 59, 89, 54, 51, 19, 76, 74],
       [39,  9, 95, 63, 26, 82, 76, 29, 13, 95],
       [41, 94, 88, 22,  4, 69, 39, 68, 52, 52],
       [36, 72, 19, 59, 30, 78, 20, 85, 37, 56],
       [31, 25, 87, 57, 56, 48,  6, 66, 62, 83],
       [ 1, 18,  0, 18, 99, 20,  3, 49,  1, 50],
       [43, 74,  0, 14, 99, 73, 30, 55, 28, 72]])

In [83]:
arr2

array([[45, 55, 54, 59, 89, 54, 51, 19, 76, 74],
       [39,  9, 95, 63, 26, 82, 76, 29, 13, 95],
       [41, 94, 88, 22,  4, 69, 39, 68, 52, 52],
       [36, 72, 19, 59, 30, 78, 20, 85, 37, 56],
       [31, 25, 87, 57, 56, 48,  6, 66, 62, 83],
       [ 1, 18,  0, 18, 99, 20,  3, 49,  1, 50],
       [43, 74,  0, 14, 99, 73, 30, 55, 28, 72],
       [47, 45, 23, 56, 48, 91, 92, 48, 16, 37],
       [20, 80, 18, 41, 73, 39, 71, 27, 84, 63],
       [36, 22, 25, 37, 79, 51, 31, 80, 17, 80]])

In [85]:
arr2[3:]

array([[36, 72, 19, 59, 30, 78, 20, 85, 37, 56],
       [31, 25, 87, 57, 56, 48,  6, 66, 62, 83],
       [ 1, 18,  0, 18, 99, 20,  3, 49,  1, 50],
       [43, 74,  0, 14, 99, 73, 30, 55, 28, 72],
       [47, 45, 23, 56, 48, 91, 92, 48, 16, 37],
       [20, 80, 18, 41, 73, 39, 71, 27, 84, 63],
       [36, 22, 25, 37, 79, 51, 31, 80, 17, 80]])

In [93]:
 arr2.mean()

48.69

In [95]:
arr2

array([[45, 55, 54, 59, 89, 54, 51, 19, 76, 74],
       [39,  9, 95, 63, 26, 82, 76, 29, 13, 95],
       [41, 94, 88, 22,  4, 69, 39, 68, 52, 52],
       [36, 72, 19, 59, 30, 78, 20, 85, 37, 56],
       [31, 25, 87, 57, 56, 48,  6, 66, 62, 83],
       [ 1, 18,  0, 18, 99, 20,  3, 49,  1, 50],
       [43, 74,  0, 14, 99, 73, 30, 55, 28, 72],
       [47, 45, 23, 56, 48, 91, 92, 48, 16, 37],
       [20, 80, 18, 41, 73, 39, 71, 27, 84, 63],
       [36, 22, 25, 37, 79, 51, 31, 80, 17, 80]])

In [97]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [105]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [113]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [ ]:
#Reshaoing has thre  format 1.orderc 2.order a o3.rder f

In [115]:
 arr.reshape(2,3,order='c')

array([[0, 1, 2],
       [3, 4, 5]])

In [117]:
arr.reshape(3,2,order='c')

array([[0, 1],
       [2, 3],
       [4, 5]])

indexing

In [119]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [123]:
row = 4
col = 5

In [125]:
col

5

In [127]:
row

4

In [129]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [131]:
mat[row,col] # we can access using varibale also

45

In [133]:
col = 6
col

6

In [135]:
mat[6] # bydefault it show row

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [137]:
mat[:,col] #with slicingshoe columun

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [139]:
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [141]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [143]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [145]:
mat[2:6,2:4] # when we use two silicing n-1 is applicable

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [147]:
mat[1:2,2:4]

array([[12, 13]])

In [149]:
mat[2:3,2:3]

array([[22]])

In [151]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [153]:
mat[2:4,3:4]

array([[23],
       [33]])

In [155]:
mat[2:4,3:5] #fisrt is row and 2nd is column

array([[23, 24],
       [33, 34]])

Masking

In [159]:
mat #we also called filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [161]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [163]:
mat<50 # it show the conditions

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [165]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [167]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [169]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [171]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])